### ISSUE TITLE
Cannot run prism as a node_module

### ISSUE THREAD

**Issue by kysonic** [stoplightio/prism#1167]
**Describe the bug**
I'm trying to use prism as node module but it doesn't work. 

**To Reproduce**

1. install prism via `yarn global add @stoplight/prism-cli`
2. run `prism mock ./src/swagger.yaml`
3. See error

```
prism mock ./src/swagger.yaml
internal/modules/cjs/loader.js:614
  throw e;
  ^

Error: No valid exports main found for '/path_to_my_project/node_modules/@stoplight/ordered-object-literal'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/Users/anton.miroshnichenko/WebDev/IX/cx-admin-schema/node_modules/@stoplight/json/index.cjs.js:1:238)
    at Module._compile (internal/modules/cjs/loader.js:1121:30) {
  code: 'MODULE_NOT_FOUND'
}
error Command failed with exit code 1.
```

**Expected behavior**
It works and runs a mock server.

**Environment (remove any that are not applicable):**
 - Library version: 3.3.4
 - OS: Mac OS X Mojavie
 - Node 13.2.0

**Comment by XVincentX** [comment]
Hey,

I can't really replicate this error. It seems like you're missing a module for some reason.

Is this happening with every OpenAPI Document or just a specific one? If it's only coming from a document, can you share it here so we can take a look?

Feel free to reopen once you have more informations.

**Comment by kysonic** [comment]
@XVincentX 
It works well on node v12.15 so let's close it for now. Thanks

**Comment by lukjaki** [comment]
I'm experiencing similar issue for fresh installation of prism. 

No valid exports main found for .../@stoplight/ordered-object-literal
