### ISSUE TITLE
Cannot do anything with `prism` command

### ISSUE THREAD

**Issue by hotmeteor** [stoplightio/prism#1193]
**Describe the bug**
Running anything using `prism` results in the same error as described below.

**To Reproduce**

1. Install Prism
2. `prism mock ../../spec.json`, `prism -v`, or even `prism`
3. See error:

```js
Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.__webpack_require__ (/Users/Adam/.npm-packages/lib/node_modules/@stoplight/prism-cli/node_modules/micri/external "worker_threads":1:1)
    at worker_threads_1 (/webpack/bootstrap:19:1)
    at Object.__webpack_require__ (/Users/Adam/.npm-packages/lib/node_modules/@stoplight/prism-cli/node_modules/micri/src/with-worker.ts:10:1)
    at default (/webpack/bootstrap:19:1)
    at Object.__webpack_require__ (/Users/Adam/.npm-packages/lib/node_modules/@stoplight/prism-cli/node_modules/micri/src/index.ts:21:8)
    at __webpack_require__ (/webpack/bootstrap:19:1)
```

**Expected behavior**
A mock server to start.

**Environment (remove any that are not applicable):**
 - Library version: latest (?)
 - OS: macOS 10.14.6
 - node v11.6.0

**Additional context**
This was a fresh install.

**Comment by XVincentX** [comment]
Hey,

We do not support node 11; please upgrade at least to node 12.

**Comment by hotmeteor** [comment]
@XVincentX Cool. Can that requirement be added to the docs?

**Comment by XVincentX** [comment]
We can do that. Do you want to open a PR? :)

**Comment by hotmeteor** [comment]
https://github.com/stoplightio/prism/pull/1194
