### ISSUE TITLE
createClientFromOperations returns unexpected error when validating requests or responses in non-mock implementation

### ISSUE THREAD

**Issue by hpl002** [stoplightio/prism#1406]
## Describe the bug

I have followed the published docs at <https://meta.stoplight.io/docs/prism/docs/guides/http-client.md> and from what i understand it should be possible to get request and response validation on non-mock requests.

I am using the prism http client in my express app to primarily validate requests against the declared schema. 
I have gotten the mock client up and running without issue, and it is returning responses as expected. 

However, when i toggle mock to false i get an unexpected error.. The schema is 100% valid.

> {
  "message": "Cannot read property 'href' of undefined",
  "stack": "TypeError: Cannot read property 'href' of undefined\n    at mockOrForward (/path/truncated/node_modules/@stoplight/prism-core/dist/factory.js:41:107)\n    at /path/truncated/node_modules/@stoplight/prism-core/dist/factory.js:58:141\n    at /path/truncated/node_modules/fp-ts/lib/Either.js:189:75\n    at /path/truncated/node_modules/fp-ts/lib/Task.js:137:44",
  "level": "error"
}

Have i misunderstood? Does response and request validation only work with mock enabled

## To Reproduce
Try running the 'createClientFromOperations' function with any combination of options that do NOT have mock enabled. 

Ex:

``` JSON
{
      mock: false,
      validateRequest: true,
      validateResponse: true,
    }
```

## My Config:

``` JSON
{
  "openapi": "3.0.0",
  "info": {
    "title": "title",
    "description": "desc",
    "version": "v1",
    "contact": { "email": "example@example.com" }
  },
  "servers": [{ "url": "http://localhost:3010/api", "description": "Sandbox" }],
  "x-flow-proxies": {
    "flow-service-proxy": { "target": "http://localhost:3020" }
  },
  "tags": [{ "name": "Account Service" }],
  "paths": {
    "/accounts": {
      "x-flow-proxy": "flow-service-proxy",
      "get": {
        "tags": ["Account Service"],
        "summary": "Gets all accounts",
        "responses": {
          "200": {
            "description": "Returns array of accounts",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "integer" },
                      "type": { "type": "string" }
                    }
                  }
                },
                "examples": {
                  "scenario-1": {
                    "summary": "List of accounts",
                    "value": [
                      { "id": 1123, "type": "Mock Checking Account" },
                      { "id": 2123, "type": "Mock Loan Account" }
                    ]
                  },
                  "scenario-2": {
                    "summary": "List of accounts",
                    "value": [
                      { "id": 11, "type": "Mock Checking Account" },
                      { "id": 223, "type": "Mock Loan Account" }
                    ]
                  },
                  "scenario-3": {
                    "summary": "List of accounts",
                    "value": [
                      { "id": 11123, "type": "Mock Checking Account" },
                      { "id": 22376, "type": "Mock Loan Account" },
                      { "id": 11456, "type": "Mock Business expenses account" },
                      { "id": 22323, "type": "Mock Savings account" },
                      { "id": 1184, "type": "Mock Business holdings account" },
                      { "id": 22322, "type": "Moch Business savings account" },
                      { "id": 11678, "type": "Mock Expired personal account" },
                      {
                        "id": 22354543,
                        "type": "Mock Personal expenses account"
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": { "description": "Not found" }
        }
      }
    },
    "/accounts/{id}": {
      "x-flow-proxy": "flow-service-proxy",
      "get": {
        "tags": ["Account Service"],
        "summary": "Gets a specific account by id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "id as integer",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a specific account by id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "type": { "type": "string" }
                  }
                },
                "examples": {
                  "scenario-1": {
                    "summary": "Single account",
                    "value": [{ "id": 1123, "type": "Mock Checking Account" }]
                  },
                  "scenario-2": {
                    "summary": "Single account",
                    "value": [{ "id": 11, "type": "Mock Checking Account" }]
                  },
                  "scenario-3": {
                    "summary": "Single account",
                    "value": [
                      { "id": 1184, "type": "Mock Business holdings account" }
                    ]
                  }
                }
              }
            }
          },
          "404": { "description": "Not found" }
        }
      }
    },
    "/accounts/{id}/transactions": {
      "x-flow-proxy": "flow-service-proxy",
      "get": {
        "x-flow-handlers": { "pathRewrite": "transactions.get.pathRewrite" },
        "tags": ["Account Service"],
        "summary": "Get transactions pertaining to account",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "id as integer",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Array of transactions",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "integer" },
                      "type": { "type": "string" },
                      "amount": { "type": "integer" }
                    }
                  }
                },
                "examples": {
                  "scenario-1": {
                    "summary": "List of transactions",
                    "value": [
                      { "id": 1, "type": "DEPOSIT", "amount": 100054 },
                      { "id": 2, "type": "WITHDRAWAL", "amount": 2505445 }
                    ]
                  },
                  "scenario-2": {
                    "summary": "List of transactions",
                    "value": [
                      { "id": 1, "type": "MockDEPOSIT", "amount": 1000 },
                      { "id": 2, "type": "Mock WITHDRAWAL", "amount": 250 },
                      { "id": 3, "type": "Mock DEPOSIT", "amount": 1000243 },
                      {
                        "id": 4,
                        "type": "Mock WITHDRAWAL",
                        "amount": 250234234
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": { "description": "Bad request" },
          "404": { "description": "Not found" }
        }
      }
    },
    "/accounts/{id}/transactions/{id}": {
      "x-flow-proxy": "flow-service-proxy",
      "get": {
        "x-flow-handlers": {
          "responseRewrite": "transaction.get.responseRewrite"
        },
        "tags": ["Account Service"],
        "summary": "Get transaction pertaining to account by id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "id as integer",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "single transaction pertaining to account",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "type": { "type": "string" },
                    "amount": { "type": "integer" }
                  }
                },
                "examples": {
                  "simple": {
                    "summary": "Transaction",
                    "value": { "type": "DEPOSIT", "amount": 1000 }
                  }
                }
              }
            }
          },
          "400": { "description": "Bad request" },
          "404": { "description": "Not found" }
        }
      }
    },
    "/post-a-string": {
      "x-flow-proxy": "flow-service-proxy",
      "post": {
        "x-flow-handlers": {
          "requestRewrite": "postAString.post.requestRewrite"
        },
        "tags": ["Account Service"],
        "summary": "Post a string and get it returned",
        "requestBody": {
          "description": "Optional description in *Markdown*",
          "required": true,
          "content": { "text/plain": { "schema": { "type": "string" } } }
        },
        "responses": { "200": { "description": "returns the posted string" } }
      }
    },
    "/custom-route": {
      "x-flow-proxy": "flow-service-proxy",
      "get": {
        "x-flow-handlers": { "route": "customRoute.get" },
        "tags": ["Account Service"],
        "summary": "Custom route",
        "responses": { "200": { "description": "OK" } }
      }
    },
    "/before-request": {
      "x-flow-proxy": "flow-service-proxy",
      "get": {
        "x-flow-handlers": {
          "beforeRequest": "beforeRequest.get.beforeRequest",
          "onProxyReq": "beforeRequest.get.onProxyReq"
        },
        "tags": ["Account Service"],
        "summary": "request with before request and onproxyrequest handler",
        "responses": { "204": { "description": "No Content" } }
      }
    },
    "/request-with-schema": {
      "x-flow-proxy": "flow-service-proxy",
      "post": {
        "tags": ["Account Service"],
        "summary": "POST request with specified schema",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "age",
                "type": "object",
                "required": ["age"],
                "properties": { "age": { "type": "integer" } }
              }
            }
          },
          "description": "Create pet",
          "required": true
        },
        "responses": { "200": { "description": "OK" } }
      }
    },
    "/get-should-have-no-body": {
      "x-flow-proxy": "flow-service-proxy",
      "get": {
        "tags": ["Account Service"],
        "summary": "get without a schema",
        "responses": { "200": { "description": "OK" } }
      }
    }
  },
  "components": {
    "schemas": {
      "age": {
        "description": "age",
        "type": "object",
        "required": ["age"],
        "properties": { "age": { "type": "integer" } }
      }
    },
    "parameters": {
      "id": {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "id as integer",
        "schema": { "type": "integer" }
      }
    }
  }
}
```

## Expected behavior

Running the exact same request with all options set to true returns the following

``` JSON
{"level":40,"time":1599561667564,"pid":54695,"hostname":"HERMANs-MacBook-Pro.local","name":"NEGOTIATOR","name":"VALIDATOR","msg":"Request did not pass the validation rules"}
{
  "message": "Invalid request body payload",
  "stack": "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY: Invalid request body payload\n    at Function.fromTemplate (/path/truncated/node_modules/@stoplight/prism-http/dist/types.js:14:23)\n    at Object.exports.createUnprocessableEntityResponse (/path/truncated/node_modules/@stoplight/prism-http/dist/mocker/index.js:66:87)\n    at /path/truncated/node_modules/@stoplight/prism-http/dist/mocker/index.js:62:19\n    at /path/truncated/node_modules/fp-ts/lib/Either.js:290:46\n    at /path/truncated/node_modules/fp-ts/lib/Reader.js:88:82\n    at /path/truncated/node_modules/fp-ts/lib/Reader.js:132:93\n    at /path/truncated/node_modules/fp-ts/lib/Reader.js:132:93\n    at /path/truncated/node_modules/fp-ts/lib/Reader.js:132:87\n    at /path/truncated/node_modules/fp-ts/lib/Reader.js:132:87\n    at mockOrForward (/path/truncated/node_modules/@stoplight/prism-core/dist/factory.js:46:15)",
  "name": "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
  "status": 422,
  "detail": "Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.",
  "additional": {
    "validation": [
      {
        "location": [
          "path"
        ],
        "severity": "Error",
        "code": "required",
        "message": "should have required property 'id'"
      }
    ]
  },
  "level": "error"
}

```

**Comment by XVincentX** [comment]
Hey @hpl002 — if you're setting `mock: false` then the `upstream` property is mandatory; that's likely the source of the error.

We have a mistake in the documentation that's being fixed right now: #1401
