### ISSUE TITLE
 SIGSEGV on Archlinux

### ISSUE THREAD

**Issue by aslafy-z** [stoplightio/prism#152]
## Bug report

SIGSEGV on Archlinux

## Environment 

Installed last release of `prism`: `2.0.14`
Using either `https://raw.githubusercontent.com/stoplightio/prism/2.x/install.sh` or manual release download.

Also tried `2.0.13`.

## Step to reproduce

- install prism with the above script on archlinux
- run command: `prism update`

## Output

```
Prism version is 2.0.14
Current Prism version is v2.0.14
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x7f25e4008af3]

runtime stack:
runtime.throw(0xe2ab78, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 37 [syscall]:
runtime.cgocall(0xafac00, 0xc000125600, 0x29)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc0001255c8 sp=0xc000125590 pc=0x40affe
net._C2func_getaddrinfo(0xc00026b830, 0x0, 0xc000294300, 0xc0001e40d8, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:92 +0x55 fp=0xc000125600 sp=0xc0001255c8 pc=0x5bdc65
net.cgoLookupIPCNAME.func1(0xc00026b830, 0x0, 0xc000294300, 0xc0001e40d8, 0xf, 0xf, 0x0)
	/usr/local/go/src/net/cgo_unix.go:149 +0x131 fp=0xc000125648 sp=0xc000125600 pc=0x5c3381
net.cgoLookupIPCNAME(0xc0002ca9a0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:149 +0x153 fp=0xc000125738 sp=0xc000125648 pc=0x5bf223
net.cgoIPLookup(0xc00014ef00, 0xc0002ca9a0, 0xe)
	/usr/local/go/src/net/cgo_unix.go:201 +0x4d fp=0xc0001257c8 sp=0xc000125738 pc=0x5bf8dd
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0001257d0 sp=0xc0001257c8 pc=0x460031
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:211 +0xad

goroutine 1 [select]:
net/http.(*Transport).getConn(0x17759c0, 0xc0003efda0, 0x0, 0xc000028e80, 0x5, 0xc0002ca9a0, 0x12, 0x0, 0x0, 0x6)
	/usr/local/go/src/net/http/transport.go:1004 +0x58e
net/http.(*Transport).roundTrip(0x17759c0, 0xc000270300, 0x203000, 0xc00076b630, 0x6960dd)
	/usr/local/go/src/net/http/transport.go:451 +0x690
net/http.(*Transport).RoundTrip(0x17759c0, 0xc000270300, 0x17759c0, 0x0, 0x0)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc000270300, 0xf346a0, 0x17759c0, 0x0, 0x0, 0x0, 0xc0001e40b0, 0xc000270228, 0xc00076b6c0, 0x1)
	/usr/local/go/src/net/http/client.go:250 +0x14b
net/http.(*Client).send(0x17dac60, 0xc000270300, 0x0, 0x0, 0x0, 0xc0001e40b0, 0x0, 0x1, 0x10)
	/usr/local/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0x17dac60, 0xc000270300, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x2a8
net/http.(*Client).Do(0x17dac60, 0xc000270300, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:509 +0x35
github.com/google/go-github/github.(*Client).Do(0xc0003405a0, 0xf3b5a0, 0xc0000240d8, 0xc000270200, 0xca7640, 0xc000426300, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/google/go-github/github/github.go:458 +0x209
github.com/google/go-github/github.(*RepositoriesService).ListReleases(0xc000340628, 0xf3b5a0, 0xc0000240d8, 0xe10ad9, 0xb, 0xe0a6b4, 0x5, 0x0, 0x0, 0x1, ...)
	/ext-go/1/src/github.com/google/go-github/github/repos_releases.go:81 +0x21f
github.com/stoplightio/bear2.0/cmd/prism/cmd/update.update(0xf2c9a4, 0x6, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/stoplightio/bear2.0/cmd/prism/cmd/update/update.go:72 +0x18d
github.com/stoplightio/bear2.0/cmd/prism/cmd/update.up(0x1777940, 0x17ff6f8, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/stoplightio/bear2.0/cmd/prism/cmd/update/update.go:57 +0x59
github.com/spf13/cobra.(*Command).execute(0x1777940, 0x17ff6f8, 0x0, 0x0, 0x1777940, 0x17ff6f8)
	/ext-go/1/src/github.com/spf13/cobra/command.go:746 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0x17774c0, 0x1777dc0, 0xc00076bf68, 0xc00076bf88)
	/ext-go/1/src/github.com/spf13/cobra/command.go:831 +0x2dc
github.com/spf13/cobra.(*Command).Execute(0x17774c0, 0x1, 0x1777dc0)
	/ext-go/1/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/ext-go/1/src/github.com/stoplightio/bear2.0/cmd/prism/main.go:33 +0x31

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 13 [syscall]:
gopkg.in/olebedev/go-duktape%2ev3._Cfunc__duk_peval_string(0x7f25d0005270, 0x7f25e43fe010, 0x0)
	_cgo_gotypes.go:648 +0x4d
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PevalString.func1(0x7f25d0005270, 0x7f25e43fe010, 0x7f25e43fe010)
	/ext-go/1/src/gopkg.in/olebedev/go-duktape.v3/api.go:883 +0x60
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PevalString(0xc0001e4000, 0xc00080a000, 0x9c592, 0x1, 0xc000055f20)
	/ext-go/1/src/gopkg.in/olebedev/go-duktape.v3/api.go:883 +0x5f
github.com/stoplightio/bear2.0/vm/runtime.(*Context).Run(0xc0001e4008, 0xc00080a000, 0x9c592, 0xe6c780, 0x1)
	/ext-go/1/src/github.com/stoplightio/bear2.0/vm/runtime/runtime.go:98 +0x5d
github.com/stoplightio/bear2.0/vm/runtime.New(0x32)
	/ext-go/1/src/github.com/stoplightio/bear2.0/vm/runtime/runtime.go:89 +0x306
github.com/stoplightio/bear2.0/vm/runtime.init.0.func1()
	/ext-go/1/src/github.com/stoplightio/bear2.0/vm/runtime/runtime_single.go:19 +0x24
created by github.com/stoplightio/bear2.0/vm/runtime.init.0
	/ext-go/1/src/github.com/stoplightio/bear2.0/vm/runtime/runtime_single.go:17 +0xa5

goroutine 34 [select]:
net.(*Resolver).LookupIPAddr(0x17da720, 0xf3b5e0, 0xc00014ecc0, 0xc0002ca9a0, 0xe, 0xc0002ca9af, 0x3, 0x1bb, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:227 +0x55f
net.(*Resolver).internetAddrList(0x17da720, 0xf3b5e0, 0xc00014ecc0, 0xe08ff5, 0x3, 0xc0002ca9a0, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:279 +0x614
net.(*Resolver).resolveAddrList(0x17da720, 0xf3b5e0, 0xc00014ecc0, 0xe09674, 0x4, 0xe08ff5, 0x3, 0xc0002ca9a0, 0x12, 0x0, ...)
	/usr/local/go/src/net/dial.go:202 +0x4fb
net.(*Dialer).DialContext(0xc00006e240, 0xf3b5a0, 0xc0000240d8, 0xe08ff5, 0x3, 0xc0002ca9a0, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:384 +0x201
net.(*Dialer).DialContext-fm(0xf3b5a0, 0xc0000240d8, 0xe08ff5, 0x3, 0xc0002ca9a0, 0x12, 0x40ce4f, 0x644ec9, 0xc0000240d8, 0xd1d020)
	/usr/local/go/src/net/http/transport.go:48 +0x73
net/http.(*Transport).dial(0x17759c0, 0xf3b5a0, 0xc0000240d8, 0xe08ff5, 0x3, 0xc0002ca9a0, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:916 +0x20f
net/http.(*Transport).dialConn(0x17759c0, 0xf3b5a0, 0xc0000240d8, 0x0, 0xc000028e80, 0x5, 0xc0002ca9a0, 0x12, 0x99, 0xda5301, ...)
	/usr/local/go/src/net/http/transport.go:1240 +0x313
net/http.(*Transport).getConn.func4(0x17759c0, 0xf3b5a0, 0xc0000240d8, 0xc0003efdd0, 0xc000314000)
	/usr/local/go/src/net/http/transport.go:999 +0x6e
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:998 +0x3d7

goroutine 36 [select]:
net.cgoLookupIP(0xf3b560, 0xc000300680, 0xc0002ca9a0, 0xe, 0x0, 0x0, 0x0, 0x17dc040, 0x4137f3, 0x7f25ea152000)
	/usr/local/go/src/net/cgo_unix.go:212 +0x17b
net.(*Resolver).lookupIP(0x17da720, 0xf3b560, 0xc000300680, 0xc0002ca9a0, 0xe, 0x0, 0xc00018dc80, 0xc00006c080, 0xc000125920, 0x8d4458)
	/usr/local/go/src/net/lookup_unix.go:95 +0x166
net.(*Resolver).lookupIP-fm(0xf3b560, 0xc000300680, 0xc0002ca9a0, 0xe, 0x431c32, 0x8, 0xc00006c080, 0x0, 0xc0001256a0)
	/usr/local/go/src/net/lookup.go:207 +0x56
net.glob..func1(0xf3b560, 0xc000300680, 0xc0003d04b0, 0xc0002ca9a0, 0xe, 0x17a3921, 0x4, 0x4, 0xc000125738, 0x476778)
	/usr/local/go/src/net/hook.go:19 +0x52
net.(*Resolver).LookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:221 +0xd8
internal/singleflight.(*Group).doCall(0x17da730, 0xc0005121e0, 0xc0002ca9a0, 0xe, 0xc0003efec0)
	/usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2a0
```

Same error happens when I try to launch a mock server:
`prism mock --spec http://petstore.swagger.io/v2/swagger.json` 

I'd be happy to have some debug steps for you if needed.

**Comment by philsturgeon** [comment]
Hey, I’m really sorry that this issue has not been replied to. We have been putting loads of work into Prism v3 and that’s where the focus will be from now on, so keep an eye on #266. We will be launching it with a new and improved installation command, and hopefully there will be no set faults there. If you notice any other bugs in v3 please make an issue, or if you find a fix for something in v2 a PR would be really appreciated. 

We’re going full open source for that one. 🙌🏻
