### ISSUE TITLE
SIGSEGV on Ubuntu

### ISSUE THREAD

**Issue by ntiss** [stoplightio/prism#181]
Prism server randomly crashes on some Ubuntu (not all computers on which I tested) when requesting a stopped API on localhost (nothing listening on port 8080).

# Step to reproduce : 

1. Run prism serve in commandline :  `./prism conduct serve -p 4020`
2. Request prism with a scenario step on localhost, either with Stoplight desktop or with curl : 
`
curl 'http://localhost:4020/v1/run' -H 'Origin: stoplight://stoplight.local' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: fr' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Connection: keep-alive' -H 'X-DevTools-Request-Id: 29479.191' --data-binary '{"env":{},"ctx":{},"specs":[],"runMap":{"scenarios":{"vafiq":{"0":true}}},"collection":{"scenarioVersion":"1.1","scenarios":{"vafiq":{"name":"New Scenario","steps":[{"type":"http","name":"","input":{"method":"patch","url":"http://localhost:8080/api/v1/doesntExists"}}]}}}}'
`

# Output
Sometimes, the error is correctly returned by Prism.
Othertimes, Prism crashes with this stacktrace : 
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fe5ac5ea448]

runtime stack:
runtime.throw(0xe2bcc1, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 79 [syscall]:
runtime.cgocall(0xafbd70, 0xc00047c600, 0x29)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc00047c5c8 sp=0xc00047c590 pc=0x40affe
net._C2func_getaddrinfo(0xc0003bd890, 0x0, 0xc0002a15f0, 0xc00000ec48, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:92 +0x55 fp=0xc00047c600 sp=0xc00047c5c8 pc=0x5bdf55
net.cgoLookupIPCNAME.func1(0xc0003bd890, 0x0, 0xc0002a15f0, 0xc00000ec48, 0xa, 0xa, 0x40d52f)
	/usr/local/go/src/net/cgo_unix.go:149 +0x131 fp=0xc00047c648 sp=0xc00047c600 pc=0x5c3671
net.cgoLookupIPCNAME(0xc0003bd870, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:149 +0x153 fp=0xc00047c738 sp=0xc00047c648 pc=0x5bf513
net.cgoIPLookup(0xc000291560, 0xc0003bd870, 0x9)
	/usr/local/go/src/net/cgo_unix.go:201 +0x4d fp=0xc00047c7c8 sp=0xc00047c738 pc=0x5bfbcd
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00047c7d0 sp=0xc00047c7c8 pc=0x4601b1
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:211 +0xad

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fe5b43fbf00, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0003c2698, 0x72, 0xc000034100, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0003c2698, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc0003c2680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc0003c2680, 0x50, 0xd7ecc0, 0xc000695a01)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00031c0a0, 0xc000695ae0, 0xc000228050, 0x87a2fd70a798189c)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).AcceptTCP(0xc00031c0a0, 0xc000695b08, 0x4917f6, 0x5c3746e4)
	/usr/local/go/src/net/tcpsock.go:247 +0x47
net/http.tcpKeepAliveListener.Accept(0xc00031c0a0, 0xc000695b58, 0x18, 0xc000000300, 0x6a9945)
	/usr/local/go/src/net/http/server.go:3232 +0x2f
net/http.(*Server).Serve(0xc0003dc820, 0xf3c540, 0xc00031c0a0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2826 +0x22f
net/http.(*Server).ListenAndServe(0xc0003dc820, 0xc0003dc820, 0x5)
	/usr/local/go/src/net/http/server.go:2764 +0xb6
net/http.ListenAndServe(0xc00031e468, 0x5, 0xf356c0, 0xc0003c2380, 0x4, 0xc00031e468)
	/usr/local/go/src/net/http/server.go:3004 +0x74
github.com/stoplightio/bear2.0/cmd/prism/cmd/conduct/serve.serve(0x1778bc0, 0xc0003a8560, 0x0, 0x2, 0x0, 0x0)
	/ext-go/1/src/github.com/stoplightio/bear2.0/cmd/prism/cmd/conduct/serve/serve.go:84 +0x150
github.com/spf13/cobra.(*Command).execute(0x1778bc0, 0xc0003a84e0, 0x2, 0x2, 0x1778bc0, 0xc0003a84e0)
	/ext-go/1/src/github.com/spf13/cobra/command.go:746 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0x17794c0, 0x1779dc0, 0xc000695f68, 0xc000695f88)
	/ext-go/1/src/github.com/spf13/cobra/command.go:831 +0x2dc
github.com/spf13/cobra.(*Command).Execute(0x17794c0, 0x1, 0x1779dc0)
	/ext-go/1/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/ext-go/1/src/github.com/stoplightio/bear2.0/cmd/prism/main.go:33 +0x31

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 71 [IO wait]:
internal/poll.runtime_pollWait(0x7fe5b43fbe30, 0x72, 0xc00047de58)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00041c018, 0x72, 0xffffffffffffff00, 0xf37080, 0x1789880)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00041c018, 0xc0003ac400, 0x1, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00041c000, 0xc0003ac4f1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00041c000, 0xc0003ac4f1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e2f0, 0xc0003ac4f1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x68
net/http.(*connReader).backgroundRead(0xc0003ac4e0)
	/usr/local/go/src/net/http/server.go:676 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:672 +0xd2

goroutine 23 [select]:
github.com/stoplightio/bear2.0/scenario.(*Conductor).Conduct(0xc0003be9a0, 0xc000329690, 0x1, 0x1)
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/conductor.go:305 +0x1d8
github.com/stoplightio/bear2.0/conductor/handlers.RunCollections(0xc00052be60)
	/ext-go/1/src/github.com/stoplightio/bear2.0/conductor/handlers/run_collection.go:92 +0x6f4
github.com/stoplightio/bear2.0/cmd/prism/cmd/conduct/serve.serve.func1(0xf3c080, 0xc0003be8c0, 0xc0002cac00)
	/ext-go/1/src/github.com/stoplightio/bear2.0/cmd/prism/cmd/conduct/serve/serve.go:66 +0xf2
net/http.HandlerFunc.ServeHTTP(0xe6d7a8, 0xf3c080, 0xc0003be8c0, 0xc0002cac00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
goji%2eio.dispatch.ServeHTTP(0xf3c080, 0xc0003be8c0, 0xc0002cac00)
	/ext-go/1/src/goji.io/dispatch.go:17 +0xba
goji%2eio.(*Mux).ServeHTTP(0xc0003c2380, 0xf3c080, 0xc0003be8c0, 0xc0002ca900)
	/ext-go/1/src/goji.io/mux.go:74 +0x1de
net/http.serverHandler.ServeHTTP(0xc0003dc820, 0xf3c080, 0xc0003be8c0, 0xc0002ca900)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000168000, 0xf3c940, 0xc000278040)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5

goroutine 75 [select, locked to thread]:
net/http.(*Transport).getConn(0x17778a0, 0xc0002a14d0, 0x0, 0xc0004c7b40, 0x4, 0xc0003bd870, 0xe, 0x0, 0x0, 0xc00039d073)
	/usr/local/go/src/net/http/transport.go:1004 +0x58e
net/http.(*Transport).roundTrip(0x17778a0, 0xc0002cae00, 0xc0002a14a0, 0xc0003bd85c, 0xc0003bd860)
	/usr/local/go/src/net/http/transport.go:451 +0x690
net/http.(*Transport).RoundTrip(0x17778a0, 0xc0002cae00, 0x17778a0, 0xbf05efa4c357697d, 0xb7a475270)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc0002cad00, 0xf35a80, 0x17778a0, 0xbf05efa4c357697d, 0xb7a475270, 0x17dd200, 0xc00000ec38, 0xbf05efa4c357697d, 0xc0004c11f0, 0x1)
	/usr/local/go/src/net/http/client.go:250 +0x14b
net/http.(*Client).send(0xc0002a13b0, 0xc0002cad00, 0xbf05efa4c357697d, 0xb7a475270, 0x17dd200, 0xc00000ec38, 0x0, 0x1, 0xc0002a0a20)
	/usr/local/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc0002a13b0, 0xc0002cad00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x2a8
net/http.(*Client).Do(0xc0002a13b0, 0xc0002cad00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:509 +0x35
github.com/franela/goreq.Request.Do(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0003bd7d5, 0x5, 0xc0004c7b40, 0x29, ...)
	/ext-go/1/src/github.com/franela/goreq/goreq.go:391 +0x2aa
github.com/stoplightio/bear2.0/scenario/http.(*Request).Invoke(0xc00039c700, 0xc00000ec10, 0x0)
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/http/request.go:782 +0x6a6
github.com/stoplightio/bear2.0/scenario.Invoker.Invoke-fm(0xc00000ec10, 0x373af90)
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/step.go:108 +0x39
gopkg.in/olebedev/go-duktape%2ev3.goFunctionCall(0x7fe5a05c5c60, 0xe6e508)
	/ext-go/1/src/gopkg.in/olebedev/go-duktape.v3/duktape.go:177 +0xb6
gopkg.in/olebedev/go-duktape%2ev3._cgoexpwrap_6b4292211010_goFunctionCall(0x7fe5a05c5c60, 0x0)
	_cgo_gotypes.go:3437 +0x2b
gopkg.in/olebedev/go-duktape%2ev3._Cfunc__duk_peval_string(0x7fe5a05c5c60, 0x373a2b0, 0x0)
	_cgo_gotypes.go:648 +0x4d
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PevalString.func1(0x7fe5a05c5c60, 0x373a2b0, 0x373a2b0)
	/ext-go/1/src/gopkg.in/olebedev/go-duktape.v3/api.go:890 +0x60
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PevalString(0xc00000e098, 0xe379be, 0x181, 0xe0c6ca, 0x6)
	/ext-go/1/src/gopkg.in/olebedev/go-duktape.v3/api.go:890 +0x5f
github.com/stoplightio/bear2.0/vm/runtime.(*Context).Run(0xc00000e0a0, 0xe379be, 0x181, 0x0, 0xffe0dd22)
	/ext-go/1/src/github.com/stoplightio/bear2.0/vm/runtime/runtime.go:98 +0x5d
github.com/stoplightio/bear2.0/scenario.(*Step).Run(0xc0002909c0, 0xc00000e0a0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/step.go:175 +0xb8
github.com/stoplightio/bear2.0/scenario.(*Scenario).Run(0xc000225ea0, 0xc00000e0a0, 0xc00052bef0, 0x7fe5a05c5c60, 0x2)
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/scenario.go:108 +0xd9
github.com/stoplightio/bear2.0/scenario.(*Scenario).Invoke(0xc000225ea0, 0xc00000e0a0, 0xc00052bef0, 0x0, 0x0)
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/scenario.go:101 +0x3f
github.com/stoplightio/bear2.0/scenario.(*Conductor).ConductScenario(0xc0003be9a0, 0xc000225ea0, 0x0)
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/conductor.go:591 +0x586
github.com/stoplightio/bear2.0/scenario.(*Conductor).ConductPhaseFor.func1(0xc0003be9a0, 0xc0002a09c0, 0xc0003be9a0, 0xc000225ea0, 0xc00054cfac, 0x5, 0xc0003bc484, 0x2)
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/conductor.go:405 +0x51
created by github.com/stoplightio/bear2.0/scenario.(*Conductor).ConductPhaseFor
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/conductor.go:403 +0x15a

goroutine 73 [semacquire]:
sync.runtime_Semacquire(0xc0003be9a8)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0003be9a0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/stoplightio/bear2.0/scenario.(*Conductor).ConductPhaseFor(0xc0003be9a0, 0xe0ffe1, 0x9, 0xc0002a09c0)
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/conductor.go:413 +0x187
github.com/stoplightio/bear2.0/scenario.(*Conductor).Conduct.func2(0xc0003be9a0, 0xc0003ea3c0, 0x2, 0x1, 0xc0003bc480, 0x2)
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/conductor.go:278 +0x557
created by github.com/stoplightio/bear2.0/scenario.(*Conductor).Conduct
	/ext-go/1/src/github.com/stoplightio/bear2.0/scenario/conductor.go:189 +0x11b

goroutine 76 [select]:
net/http.setRequestCancel.func3(0x0, 0xc0002a14a0, 0xc0002288c0, 0xc0003bd85c, 0xc000342de0)
	/usr/local/go/src/net/http/client.go:321 +0xcf
created by net/http.setRequestCancel
	/usr/local/go/src/net/http/client.go:320 +0x24e

goroutine 77 [select]:
net.(*Resolver).LookupIPAddr(0x17dc980, 0xf3c9c0, 0xc0002914a0, 0xc0003bd870, 0x9, 0xc0003bd87a, 0x4, 0x1f90, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:227 +0x55f
net.(*Resolver).internetAddrList(0x17dc980, 0xf3c9c0, 0xc0002914a0, 0xe0a175, 0x3, 0xc0003bd870, 0xe, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:279 +0x614
net.(*Resolver).resolveAddrList(0x17dc980, 0xf3c9c0, 0xc0002914a0, 0xe0a7f4, 0x4, 0xe0a175, 0x3, 0xc0003bd870, 0xe, 0x0, ...)
	/usr/local/go/src/net/dial.go:202 +0x4fb
net.(*Dialer).DialContext(0x1776980, 0xf3c980, 0xc0000280a8, 0xe0a175, 0x3, 0xc0003bd870, 0xe, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:384 +0x201
net.(*Dialer).Dial(0x1776980, 0xe0a175, 0x3, 0xc0003bd870, 0xe, 0x60, 0x110, 0x110, 0xc0004f9560)
	/usr/local/go/src/net/dial.go:329 +0x75
net.(*Dialer).Dial-fm(0xe0a175, 0x3, 0xc0003bd870, 0xe, 0xc000291440, 0xc000067ae0, 0x40ce53, 0x6453d9)
	/ext-go/1/src/github.com/google/martian/proxy.go:74 +0x52
net/http.(*Transport).dial(0x17778a0, 0xf3c980, 0xc0000280a8, 0xe0a175, 0x3, 0xc0003bd870, 0xe, 0x17d0100, 0xd670c0, 0xc0002909c0, ...)
	/usr/local/go/src/net/http/transport.go:919 +0x7b
net/http.(*Transport).dialConn(0x17778a0, 0xf3c980, 0xc0000280a8, 0x0, 0xc0004c7b40, 0x4, 0xc0003bd870, 0xe, 0x0, 0xc000342720, ...)
	/usr/local/go/src/net/http/transport.go:1240 +0x313
net/http.(*Transport).getConn.func4(0x17778a0, 0xf3c980, 0xc0000280a8, 0xc0002a1500, 0xc000342e40)
	/usr/local/go/src/net/http/transport.go:999 +0x6e
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:998 +0x3d7

goroutine 78 [select]:
net.cgoLookupIP(0xf3c940, 0xc000034fc0, 0xc0003bd870, 0x9, 0x0, 0xc0004b4f80, 0x0, 0x40c315, 0x7fe58c002570, 0x0)
	/usr/local/go/src/net/cgo_unix.go:212 +0x17b
net.(*Resolver).lookupIP(0x17dc980, 0xf3c940, 0xc000034fc0, 0xc0003bd870, 0x9, 0xc00047c640, 0xc000199b00, 0xc000278280, 0xc00047c628, 0x45cda0)
	/usr/local/go/src/net/lookup_unix.go:95 +0x166
net.(*Resolver).lookupIP-fm(0xf3c940, 0xc000034fc0, 0xc0003bd870, 0x9, 0x431d32, 0xc000000008, 0xc000278280, 0x40d52f, 0xc00047c6a0)
	/usr/local/go/src/net/lookup.go:207 +0x56
net.glob..func1(0xf3c940, 0xc000034fc0, 0xc0002e2720, 0xc0003bd870, 0x9, 0x0, 0xc00000e770, 0xc0002fcf30, 0xc0000818b8, 0x45b150)
	/usr/local/go/src/net/hook.go:19 +0x52
net.(*Resolver).LookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:221 +0xd8
internal/singleflight.(*Group).doCall(0x17dc990, 0xc000228960, 0xc0003bd870, 0x9, 0xc0002a1590)
	/usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2a0
```
Only few tries leads to the crash.

# When using Stoplight desktop 4.7.0
Same behaviour : the stacktrace is in the console of the Developer Tools.
And after the crash, Stoplight needs to be restarted or reloaded in order to relaunch prism conductor.

# Configuration
Prism 2.0.17 (but also reproduced with 2.0.16)

Linux LINXXXXXXX 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by olof-nord** [comment]
I have the same issue, reproducable with "prism login".

Prism version is 2.0.17
Linux 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64 GNU/Linux

**Comment by philsturgeon** [comment]
Hey folks, sorry this is giving you trouble, but we're focusing on Prism v3, the TypeScript based rewrite with a stronger focus on mocking. As such we wont be able to dedicate resources to figure out what is causing this crash. 

Maybe you can debug this a bit further and give us more to go? If it's simple enough we can open this back up and sneak in a fix.
