### ISSUE TITLE
Self referencing schema causing an error

### ISSUE THREAD

**Issue by brian-geoghegan** [stoplightio/prism#2081]
This particular piece of self referencing and reflects the actual API response.
## Context

`    content:
      type: object
      properties:
        text:
          type: string
          description: Text content
        type:
          type: string
          description: Content type (e.g. text, link, image)
        metadata:
          type: object
          description: Content metadata (e.g. href, src, alt)
        children:
          type: array
          description: sub-content
          items:
            $ref: '#/components/schemas/content'
`

## Current Behavior

`{
    "type": "https://stoplight.io/prism/errors#UNKNOWN",
    "title": "Error: Prop not found: paths (#/paths/~1coreapi~1recent-news~1v1~1search/get/responses/200/content/application~1json; charset=utf-8/schema/allOf/1/properties/articles/items/properties/body/items)\n    at Object.getLocalRef (/home/node/app/node_modules/json-schema-faker/dist/main.cjs.js:932:17)\n    at recursiveUtil.resolveSchema (/home/node/app/node_modules/json-schema-faker/dist/main.cjs.js:2252:25)\n    at traverse (/home/node/app/node_modules/json-schema-faker/dist/main.cjs.js:2079:16)\n    at Object.arrayType [as array] (/home/node/app/node_modules/json-schema-faker/dist/main.cjs.js:1567:25)\n    at traverse (/home/node/app/node_modules/json-schema-faker/dist/main.cjs.js:2155:44)\n    at /home/node/app/node_modules/json-schema-faker/dist/main.cjs.js:2188:52\n    at Array.forEach (<anonymous>)\n    at traverse (/home/node/app/node_modules/json-schema-faker/dist/main.cjs.js:2184:27)\n    at Object.objectType [as object] (/home/node/app/node_modules/json-schema-faker/dist/main.cjs.js:1851:14)\n    at traverse (/home/node/app/node_modules/json-schema-faker/dist/main.cjs.js:2155:44) in /properties/articles/items/0/properties/body/items/0/properties/children",
    "status": 500,
    "detail": ""
}`

## Expected Behavior

Expect prism to create the mock request and response here

## Steps to Reproduce

1. Create a self referencing component
2. Witness the bug

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by daniel-white** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Tacocat-5eb9bc4a1fddfe30b94f78b1/issues/stoplightio/prism/2081?planning-poker) with ZenHub @brendarearden @chohmann @EdVinyard @fcasad

**Comment by ryotrellim** [comment]
Doc todo: Add information about the maximum depth that prism will analyze recursively.

**Comment by daniel-white** [comment]
hey @brian-geoghegan - i just added a couple tests in #2086 to cover this case using your sample (assuming oas 3.x). they passed locally for me. can you review these to see if they fit your use case?

**Comment by rattrayalex** [comment]
I think this is the same issue but I'm not totally sure. 

We get this traceback:

```
[1:16:12 PM] › [HTTP SERVER] post /recursion/shared/responses/mutual-a ✖  error     Request terminated with error: Error: Error: Prop not found: __bundled__ (#/__bundled__/schema)
    at Object.getLocalRef (/Users/ralex/code/stainless/node_modules/json-schema-faker/dist/main.cjs.js:932:17)
    at Object.recursiveUtil.resolveSchema (/Users/ralex/code/stainless/node_modules/json-schema-faker/dist/main.cjs.js:2252:25)
    at /Users/ralex/code/stainless/node_modules/json-schema-faker/dist/main.cjs.js:2307:39
    at Array.forEach (<anonymous>)
    at recursiveUtil.resolveSchema (/Users/ralex/code/stainless/node_modules/json-schema-faker/dist/main.cjs.js:2305:26)
    at traverse (/Users/ralex/code/stainless/node_modules/json-schema-faker/dist/main.cjs.js:2079:16)
    at Object.objectType [as object] (/Users/ralex/code/stainless/node_modules/json-schema-faker/dist/main.cjs.js:1851:14)
    at traverse (/Users/ralex/code/stainless/node_modules/json-schema-faker/dist/main.cjs.js:2155:44)
    at /Users/ralex/code/stainless/node_modules/json-schema-faker/dist/main.cjs.js:2188:52
    at Array.forEach (<anonymous>) in /properties/b
```

With this OAS:

```yaml
paths:
  /responses/mutual-a:
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SharedModelMutualRecursionA'
components:
  schemas:
    SharedModelMutualRecursionA:
      type: object
      properties:
        b:
          $ref: '#/components/schemas/SharedModelMutualRecursionB'
      required: []

    SharedModelMutualRecursionB:
      type: object
      properties:
        a:
          $ref: '#/components/schemas/SharedModelMutualRecursionA'
      required: []
```

It looks like an issue in json-schema-faker, so I'll see about reporting there, but it may be good to wrap calls to that library in a try/catch if possible.
