### ISSUE TITLE
TypeError: Cannot set property $ref of #<Object> which has only a getter

### ISSUE THREAD

**Issue by keyboardsamurai** [stoplightio/prism#2090]
When using the mock server with the [attached openapi definition](https://github.com/stoplightio/prism/files/9127719/openapi.txt) that validates just fine at https://validator.swagger.io/ I consistently get the following error when using ```prism mock ./openapi.yml``` instead of starting the mock server:

```
TypeError: Cannot set property $ref of #<Object> which has only a getter
    at Object.onProperty (/Users/user/.nvm/versions/node/v18.6.0/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.cjs.js:1:4846)
    at _traverse (/Users/user/.nvm/versions/node/v18.6.0/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.cjs.js:1:3579)
    at _traverse (/Users/user/.nvm/versions/node/v18.6.0/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.cjs.js:1:3672)
    at _traverse (/Users/user/.nvm/versions/node/v18.6.0/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.cjs.js:1:3672)
    at _traverse (/Users/user/.nvm/versions/node/v18.6.0/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.cjs.js:1:3672)
    at _traverse (/Users/user/.nvm/versions/node/v18.6.0/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.cjs.js:1:3672)
    at _traverse (/Users/user/.nvm/versions/node/v18.6.0/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.cjs.js:1:3672)
    at _traverse (/Users/user/.nvm/versions/node/v18.6.0/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.cjs.js:1:3672)
    at _traverse (/Users/user/.nvm/versions/node/v18.6.0/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.cjs.js:1:3672)
    at _traverse (/Users/user/.nvm/versions/node/v18.6.0/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.cjs.js:1:3672)
```

Environment: MacOS 12.4, NodeJS 18.6.0 and 16.15.0 (tried both)

**Comment by chohmann** [comment]
Hi @keyboardsamurai, thank you for reporting this! Could you provide a minimum reproducible example that illustrates this issue? That will help us pinpoint exactly what about a ref could cause this.

**Comment by keyboardsamurai** [comment]
Hi @chohmann, thank you for taking the time to look into this issue. I'd be happy to provide a working setup but I'm not sure what I should gather besides the attached spec. Do you have something specific in mind, like a dockerized demo of the issue?

**Comment by chohmann** [comment]
Hi @keyboardsamurai! I was thinking just a smaller spec with one ref that illustrates the issue. It's hard to tell from the spec you provided exactly which ref is causing the issue. So a very simple spec would be greatly appreciated!

**Comment by keyboardsamurai** [comment]
@chohmann I was able to narrow this particular issue down to the cyclic dependency for PydanticDocument described in this minimal openapi spec below. Hope this helps

```
openapi: 3.0.2
info:
  title: My Jina Service
  description: Desc
  version: 3.6.13
paths:
  "/update":
    put:
      summary: "/Update"
      description: Post data requests to the Flow. Executors with `@requests(on="/update")`
        will respond.
      operationId: _update_update_put
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/JinaRequestModel"
        required: true
components:
  schemas:
    JinaRequestModel:
      title: JinaRequestModel
      type: object
      properties:
        data:
          anyOf:
            - type: array
              items:
                "$ref": "#/components/schemas/PydanticDocument"
    PydanticDocument:
      title: PydanticDocument
      type: object
      properties:
        chunks:
          title: Chunks
          type: array
          items:
            "$ref": "#/components/schemas/PydanticDocument"

```

**Comment by ryotrellim** [comment]
A previous ticket regarding circular references: https://github.com/stoplightio/prism/issues/1456

**Comment by theold190** [comment]
I see same error when testing with docker image **v4.10.1**. It fails to start the mock:

```
 [11:35:16 AM] › [CLI] …  awaiting  Starting Prism…
 [11:35:18 AM] › [CLI] ✖  fatal     Cannot set property $ref of #<Object> which has only a getter
```

But I am able to start Prism mock when using docker image **v4.10.0**.

So maybe there was a regression in v4.10.1?

**Comment by utadachiren** [comment]
I am able to start Prism mock when using v4.2.5.
I install prism by `yarn add @stoplight/prism-cli@v4.2.5`
I see same error when using v4.10.0 and v4.10.1.

**Comment by hieucd04** [comment]
I downloaded Stoplight Studio here: https://github.com/stoplightio/studio/releases

And with the assumption that Stoplight Studio "Mocks" feature is powered by Prism:
- Version "v2.8.1" also has this issue (toggle Dev Tools to see it)
- Whereas, version "2.8.1" doesn't
(the difference is the letter "v" at the beginning)

**Comment by steffidg** [comment]
I'm encountering the same issue on my end. After trying it out, it appears that my spec stopped successfully compiling on 
v4.9.x and  above.

**Comment by chohmann** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Tacocat-5eb9bc4a1fddfe30b94f78b1/issues/stoplightio/prism/2090?planning-poker) with ZenHub @brendarearden @daniel-white @EdVinyard @fcasad

**Comment by daniel-white** [comment]
thanks all. i'm starting to take a look to see what is going on

**Comment by daniel-white** [comment]
i'm not able to _directly_ reproduce in my dev environment but running this spec under docker does cause problems (both node16 and node18)

**Comment by daniel-white** [comment]
hey @keyboardsamurai  @steffidg @hieucd04 @theold190 - i just cut 4.10.3. i'm hoping this solves your use cases. if not please come back and open new issues with new examples. thanks!
