### ISSUE TITLE
Prism mock call after reponse content-type module gives error and exits prism

### ISSUE THREAD

**Issue by tommasop** [stoplightio/prism#2352]
```
sample_api on main …
➜ prism mock -d sample_api.json 
[6:03:45 PM] › [CLI] …  awaiting  Starting Prism…
[6:03:45 PM] › [CLI] ℹ  info      POST       http://127.0.0.1:4010/v1/ixi/tuners
[6:03:45 PM] › [CLI] ▶  start     Prism is listening on http://127.0.0.1:4010
[6:04:01 PM] › [HTTP SERVER] post /v1/ixi/tuners ℹ  info      Request received
[6:04:01 PM] ›     [NEGOTIATOR] ℹ  info      Request contains an accept header: application/json
[6:04:01 PM] ›     [VALIDATOR] ✔  success   The request passed the validation rules. Looking for the best response
[6:04:01 PM] ›     [NEGOTIATOR] ✔  success   Found a compatible content for application/json
[6:04:01 PM] ›     [NEGOTIATOR] ✔  success   Responding with the requested status code 201
[6:04:01 PM] ›     [NEGOTIATOR] ℹ  info      > Responding with "201"

/home/tommasop/.asdf/installs/nodejs/18.12.1/lib/node_modules/@stoplight/prism-cli/node_modules/content-type/index.js:126
    throw new TypeError('invalid media type')
          ^
TypeError: invalid media type
    at parse (/home/tommasop/.asdf/installs/nodejs/18.12.1/lib/node_modules/@stoplight/prism-cli/node_modules/content-type/index.js:126:11)
    at /home/tommasop/.asdf/installs/nodejs/18.12.1/lib/node_modules/@stoplight/prism-cli/node_modules/fp-ts/lib/Option.js:210:71
    at pipe (/home/tommasop/.asdf/installs/nodejs/18.12.1/lib/node_modules/@stoplight/prism-cli/node_modules/fp-ts/lib/function.js:305:29)
    at validateMediaType (/home/tommasop/.asdf/installs/nodejs/18.12.1/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/prism-http/dist/validator/index.js:65:72)
    at /home/tommasop/.asdf/installs/nodejs/18.12.1/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/prism-http/dist/validator/index.js:77:368
    at /home/tommasop/.asdf/installs/nodejs/18.12.1/lib/node_modules/@stoplight/prism-cli/node_modules/fp-ts/lib/Option.js:646:53
    at pipe (/home/tommasop/.asdf/installs/nodejs/18.12.1/lib/node_modules/@stoplight/prism-cli/node_modules/fp-ts/lib/function.js:301:20)
    at /home/tommasop/.asdf/installs/nodejs/18.12.1/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/prism-http/dist/validator/index.js:77:173
```

## Current Behavior
prism process exits and response is never returned

## Expected Behavior
prism must return response and prism process must not exit

## Steps to Reproduce

OpenApi v2 sample file:

```
{
  "info": {
    "title": "Sample API",
    "description": "Sample API",
    "version": "20230801"
  },
  "swagger": "2.0",
  "produces": [
    "application/xml",
    "application/json",
    "application/octet-stream",
    "text/plain"
  ],
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "X-Api-Key",
      "in": "header"
    }
  },
  "host": "localhost:3000",
  "tags": [
    {
      "name": "IXI",
      "description": "iXi API"
    }
  ],
  "paths": {
    "/v1/ixi/tuners": {
      "post": {
        "summary": "Create tuner",
        "description": "This method registers new tuner.",
        "produces": [
          "json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "V1IxiTuners",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/postV1IxiTuners"
            }
          }
        ],
        "security": [
          {
            "api_key": {}
          }
        ],
        "responses": {
          "201": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/TunerDetails"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/UnprocessableEntityError"
            }
          }
        },
        "tags": [
          "IXI"
        ],
        "operationId": "postV1IxiTuners"
      }
    }
  },
  "definitions": {
    "BadRequestError": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "default": "ERROR",
          "description": "Result status, mostly `ERROR`"
        },
        "code": {
          "type": "string",
          "default": "BAD_REQUEST",
          "description": "Error code."
        },
        "errors": {
          "type": "array",
          "items": {
            "type": "string",
            "default": "400 Bad Request"
          },
          "description": "Array of errors strings with more detailed information about occured errors."
        }
      }
    },
    "UnauthorizedError": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "default": "ERROR",
          "description": "Result status, mostly `ERROR`"
        },
        "code": {
          "type": "string",
          "default": "UNAUTHORIZED",
          "description": "Error code."
        },
        "errors": {
          "type": "array",
          "items": {
            "type": "string",
            "default": "401 Unauthorized"
          },
          "description": "Array of errors strings with more detailed information about occured errors."
        }
      }
    },
    "NotFoundError": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "default": "ERROR",
          "description": "Result status, mostly `ERROR`"
        },
        "code": {
          "type": "string",
          "default": "NOT_FOUND",
          "description": "Error code."
        },
        "errors": {
          "type": "array",
          "items": {
            "type": "string",
            "default": "404 Not Found"
          },
          "description": "Array of errors strings with more detailed information about occured errors."
        }
      }
    },
    "UnprocessableEntityError": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "default": "ERROR",
          "description": "Result status, mostly `ERROR`"
        },
        "code": {
          "type": "string",
          "default": "UNPROCESSABLE_ENTITY",
          "description": "Error code."
        },
        "errors": {
          "type": "array",
          "items": {
            "type": "string",
            "default": "422 Unprocessable Entity"
          },
          "description": "Array of errors strings with more detailed information about occured errors."
        }
      }
    },
    "TunerDetails": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "default": "OK",
          "description": "Result status, mostly one of `OK|ERROR`"
        },
        "tuner": {
          "$ref": "#/definitions/TunerRow"
        }
      },
      "description": "This method registers new tuner."
    },
    "TunerRow": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32",
          "default": 666,
          "description": "id"
        },
        "name": {
          "type": "string",
          "default": "User #666",
          "description": "name"
        },
        "email": {
          "type": "string",
          "default": "666@user.com",
          "description": "email"
        },
        "basic_account": {
          "type": "boolean",
          "default": "true",
          "description": "basic_account"
        },
        "locale": {
          "type": "string",
          "default": "RU"
        },
        "registering_app": {
          "type": "string",
          "default": "ixi"
        },
        "first_name": {
          "type": "string",
          "default": "",
          "description": "first_name"
        },
        "last_name": {
          "type": "string",
          "default": "",
          "description": "last_name"
        },
        "company_name": {
          "type": "string",
          "default": ""
        },
        "address": {
          "type": "string",
          "default": ""
        },
        "zip": {
          "type": "string",
          "default": ""
        },
        "city": {
          "type": "string",
          "default": ""
        },
        "country": {
          "type": "string",
          "default": ""
        },
        "business": {
          "type": "boolean",
          "default": ""
        },
        "vat_id": {
          "type": "string",
          "default": ""
        },
        "phone1": {
          "type": "string",
          "default": ""
        },
        "phone2": {
          "type": "string",
          "default": ""
        },
        "www": {
          "type": "string",
          "default": ""
        },
        "subject_type": {
          "type": "string",
          "default": ""
        },
        "fiscal_code": {
          "type": "string",
          "default": ""
        },
        "sdi_code": {
          "type": "string",
          "default": ""
        },
        "pec_sdi": {
          "type": "string",
          "default": ""
        },
        "esolver_id": {
          "type": "string",
          "default": ""
        }
      }
    },
    "postV1IxiTuners": {
      "type": "object",
      "properties": {
        "tuner": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "description": "User email (*required)"
            },
            "name": {
              "type": "string",
              "description": "User name (*required)"
            },
            "password": {
              "type": "string",
              "description": "User password (*required)"
            },
            "password_confirmation": {
              "type": "string",
              "description": "User password (*required)"
            },
            "login": {
              "type": "string",
              "description": "User login"
            },
            "locale": {
              "type": "string",
              "description": "Locale (eg 'pl')"
            },
            "timezone": {
              "type": "string",
              "description": "Timezone"
            }
          },
          "required": [
            "email",
            "name",
            "password",
            "password_confirmation"
          ]
        }
      },
      "required": [
        "tuner"
      ],
      "description": "Create tuner."
    }
  }
}
```

1. `npm install -g @stoplight/prism-cli`
2. `prism mock -d sample_api.json`
3. run following api request:

```
13:33:48.238 request_id=F3mzzP08HHWuEBIAAATB [error] POST http://localhost:4010/v1/ixi/tuners -> error: :closed (92.682 ms)
13:33:48.238 request_id=F3mzzP08HHWuEBIAAATB [debug] 
>>> REQUEST >>>
(no query)
Accept: application/json
Content-Type: application/json
X-Api-Key: wwegwgwgwgwgwegwgwegwegwegwegwegwegwegwegweg
content-type: application/json

{"tuner":{"email":"some_email@example.com","name":"some first_name some last_name","password":"some encrypted_password","password_confirmation":"some encrypted_password"}}

<<< RESPONSE ERROR <<<
:closed
```

## Environment
NodeJs 18.12.1 (asdf)
Prism 5.2.0
PopOS 22.04

**Comment by EdVinyard** [comment]
@tommasop , thanks for your report.  We agree that Prism 
1. shouldn't crash, and
2. should provide a more useful error message than "invalid media type".

In this case, "invalid media type" refers to `$.paths./v1/ixi/tuners.post.produces`.  When we changed that from "json" to "application/json", the following request worked for us.

```sh
curl -v http://localhost:4010/v1/ixi/tuners \
    -H 'Content-Type: application/json' \
    -H 'X-Api-Key: abc123' \
    --data-raw '{"tuner":{"email":"some_email@example.com","name":"some first_name some last_name","password":"some encrypted_password","password_confirmation":"some encrypted_password"}}'
```

**Comment by tommasop** [comment]
@EdVinyard thanks for your prompt reply and sorry for my delay, I was on holiday.
I will pay attention to use the correct content type.

**Comment by tommasop** [comment]
@EdVinyard unfortunately it seems it is not a content type problem:
![image](https://github.com/stoplightio/prism/assets/53027/22d00111-64bb-49fa-9513-4c2160c15239)

I did the call exactly as yours but prism crashes nonetheless.

Can it be a nodejs version problem (or a content-type version problem)?

**Comment by tommasop** [comment]
@EdVinyard same problem with node 18.18.0

**Comment by EdVinyard** [comment]
@tommasop , can you confirm that you changed `sample_api.json` as I mentioned before you retested?  I saved your JSON file as `issue_2352.before.json`, copied it to `issue_2352.after.json` and changed the "after" file as:

```sh
% diff issue_2352.before.json issue_2352.after.json
28c28
<         "produces": ["json"],
---
>         "produces": ["application/json"],
```

_With_ that change in the spec file, I run Prism and make the request using curl and I see...

```sh
% node --version; npm --version; npx prism --version; npx prism mock -d issue_2352.after.json
v18.18.0
9.8.1
5.2.0
[5:13:53 PM] › [CLI] …  awaiting  Starting Prism…
[5:13:53 PM] › [CLI] ℹ  info      POST       http://127.0.0.1:4010/v1/ixi/tuners
[5:13:53 PM] › [CLI] ▶  start     Prism is listening on http://127.0.0.1:4010
[5:13:55 PM] › [HTTP SERVER] post /v1/ixi/tuners ℹ  info      Request received
[5:13:55 PM] ›     [NEGOTIATOR] ℹ  info      Request contains an accept header: */*
[5:13:55 PM] ›     [VALIDATOR] ✔  success   The request passed the validation rules. Looking for the best response
[5:13:55 PM] ›     [NEGOTIATOR] ✔  success   Found a compatible content for */*
[5:13:55 PM] ›     [NEGOTIATOR] ✔  success   Responding with the requested status code 201
[5:13:55 PM] ›     [NEGOTIATOR] ℹ  info      > Responding with "201"
```

...and that succeeds.

However, _without_ the change to the spec file, I see exactly what you reported...

```sh
% node --version; npm --version; npx prism --version; npx prism mock -d issue_2352.before.json
v18.18.0
9.8.1
5.2.0
[5:23:13 PM] › [CLI] …  awaiting  Starting Prism…
[5:23:13 PM] › [CLI] ℹ  info      POST       http://127.0.0.1:4010/v1/ixi/tuners
[5:23:13 PM] › [CLI] ▶  start     Prism is listening on http://127.0.0.1:4010
[5:23:16 PM] › [HTTP SERVER] post /v1/ixi/tuners ℹ  info      Request received
[5:23:16 PM] ›     [NEGOTIATOR] ℹ  info      Request contains an accept header: */*
[5:23:16 PM] ›     [VALIDATOR] ✔  success   The request passed the validation rules. Looking for the best response
[5:23:16 PM] ›     [NEGOTIATOR] ✔  success   Found a compatible content for */*
[5:23:16 PM] ›     [NEGOTIATOR] ✔  success   Responding with the requested status code 201
[5:23:16 PM] ›     [NEGOTIATOR] ℹ  info      > Responding with "201"

/Users/evinyard/.nvm/versions/node/v18.18.0/lib/node_modules/@stoplight/prism-cli/node_modules/content-type/index.js:126
    throw new TypeError('invalid media type')
          ^
TypeError: invalid media type
...
```

Thanks for your patience, and I appreciate any additional information you can provide.
