### ISSUE TITLE
Cannot find module 'json-schema-faker'

### ISSUE THREAD

**Issue by xieyx** [stoplightio/prism#283]
when i run
```
prism mock https://raw.githack.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml
```
show me
```
Error: Cannot find module 'json-schema-faker'
    at Object.<anonymous> (~/.nvm/versions/node/v8.9.3/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/prism-http/lib/mocker/generator/JSONSchemaExampleGenerator.js:5:11)
```

**Comment by philsturgeon** [comment]
Hey, let’s get this sorted! What was your installation method and which version are you running, and are we on windows, OS X or Linux here?

**Comment by tbarn** [comment]
I get the same error when I do: 

```
➜  Stoplight npm install -g @stoplight/prism-cli@alpha
npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated bourne@1.1.2: This module has moved and is now available at @hapi/bourne. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
/Users/taylorbarnett/.nvm/versions/node/v10.15.3/bin/prism -> /Users/taylorbarnett/.nvm/versions/node/v10.15.3/lib/node_modules/@stoplight/prism-cli/bin/run
+ @stoplight/prism-cli@3.0.0-alpha.1
added 288 packages from 276 contributors in 44.784s
➜  Stoplight prism mock https://raw.githack.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml

Error: Cannot find module 'json-schema-faker'
    at Object.<anonymous> (~/.nvm/versions/node/v10.15.3/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/prism-http/lib/mocker/generator/JSONSchemaExampleGenerator.js:5:11)
```

**Comment by XVincentX** [comment]
This is happening because we're using the `resolutions` property in the package.json which is working  exclusively with yarn. We'll figure out a way to get rid of this.

In meantime, @xieyx, can you try to install Spectral using the binaries or `yarn`?

`yarn global add @stoplight/prism-cli`

**Comment by XVincentX** [comment]
@xieyx This should now be fixed in the latest alpha. Just upgrade your local installation with the same command you ran:

`npm i -g @stoplight/prism-cli@alpha` or also `npm i -g @stoplight/prism-cli`

**Comment by xieyx** [comment]
@XVincentX Thanks. It's ok now.
