### ISSUE TITLE
bug: createServer() does not work without second argument

### ISSUE THREAD

**Issue by takeru0757** [stoplightio/prism#349]
**Describe the bug**

`createServer()` (`http-server`) does not work without second argument.

**To Reproduce**

The code below (refer to README) causes a error:

```js
const { createServer } = require('@stoplight/prism-http-server');

const server = createServer({
  path: './api.oas2.json',
});

server.listen(3000).then(() => {
  console.log('server is listening!');
});
```

```
/node_modules/@stoplight/prism-http-server/lib/server.js:41
    const { components = {}, config } = opts;
            ^

TypeError: Cannot destructure property `components` of 'undefined' or 'null'.
    at exports.createServer (/node_modules/@stoplight/prism-http-server/lib/server.js:41:41)
    at Object.<anonymous> (/stub-server.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

This code worked:

```js
const { createServer } = require('@stoplight/prism-http-server');

const server = createServer({
  path: './api.oas2.json',
}, {}); // <= empty object

server.listen(3000).then(() => {
  console.log('server is listening!');
});
```

**Expected behavior**

`createServer()` should work without second argument (or fix README).

**Desktop (please complete the following information):**

- OS: macOS 10.14.4
- Prism Version: prism-http-server@^3.0.0-alpha.14
- Install method: yarn

**Comment by philsturgeon** [comment]
@XVincentX lets fix the README and also mention this API is experimental, along with the HTTP Client API.
