### ISSUE TITLE
Fresh installation not runnable

### ISSUE THREAD

**Issue by tobbbles** [stoplightio/prism#767]
**Describe the bug**
Running Prism from a fresh installation on Node v13.0.1 results in the following error
```
/Users/tobbbles/.asdf/installs/nodejs/13.0.1/.npm/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/http-spec/src/index.ts:1
export * from './oas2';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/tobbbles/.asdf/installs/nodejs/13.0.1/.npm/lib/node_modules/@stoplight/prism-cli/dist/util/getHttpOperations.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
```

**To Reproduce**

1. Install
```
npm install -g @stoplight/prism-cli
```

2. Run
```
$ prism
```

**Expected behavior**
For the prism-cli to be runnable on a new install, without any additional steps

**Environment (remove any that are not applicable):**
 - Library version: 3.1.1
 - OS: Mac OSX Mojave 10.14.6
 - Browser: N/A
 - Terminal env: zsh
 - npm version: 6.12.1
 - Node version: v13.0.1

**Additional context**
This is the first time I've attempted to install and use prism

**Comment by XVincentX** [comment]
@tobbbles Can you try this again? We had a problem with an internal library being published because of the recent CircleCI outage. It should be all good now.

**Comment by tobbbles** [comment]
Re-installed an working as expected - thanks!

**Comment by pawelchrobak** [comment]
Hi, I'm experiencing the same issue.

I've tried to use prism for the first time. Tried on node 12.16.1 and 13.11.0.

Prism package version @stoplight/prism-cli@3.3.1
Npm 6.13.7
Node 13.11.0
OS win10 x64

```
C:\Users\chrobak\AppData\Roaming\nvm\v13.11.0\node_modules\@stoplight\prism-cli\node_modules\@stoplight\http-spec\index.js:1
export * from './oas2';
^^^^^^

SyntaxError: Unexpected token 'export'
[90m    at wrapSafe (internal/modules/cjs/loader.js:1063:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1111:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:996:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:896:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1036:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\Chrobak\AppData\Roaming\nvm\v13.11.0\node_modules\[4m@stoplight[24m\prism-cli\node_modules\[4m@stoplight[24m\prism-http\dist\getHttpOperations.js:3:21)
[90m    at Module._compile (internal/modules/cjs/loader.js:1147:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)[39m
```

**Comment by eebonillo** [comment]
Hi,
I'm suffering the same error:

/usr/local/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/http-spec/index.js:1
export * from './oas2';
^^^^^^

SyntaxError: Unexpected token 'export'
at wrapSafe (internal/modules/cjs/loader.js:1063:16)
at Module._compile (internal/modules/cjs/loader.js:1111:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)

Shall we open another issue? It's the first time I use this tool to report errors.

**Comment by XVincentX** [comment]
Yes we had a mispublish of one of our libraries. We should be back online in some hours.

**Comment by XVincentX** [comment]
@eebonillo @pawelchrobak It should be back working correctly. Can you verify?

**Comment by pawelchrobak** [comment]
Yes, it works now. Awesome! Thanks.
